In [1]:
pip install tensorflow

Note: you may need to restart the kernel to use updated packages.Collecting tensorflow

  Created wheel for clang: filename=clang-5.0-py3-none-any.whl size=30702 sha256=c282cb5e48a79c968b4291fd7b49dc0fb650cb102ef01feea30953d802f69dde
  Stored in directory: c:\users\hp\appdata\local\pip\cache\wheels\f1\60\77\22b9b5887bd47801796a856f47650d9789c74dc3161a26d608
  Created wheel for termcolor: filename=termcolor-1.1.0-py3-none-any.whl size=4829 sha256=f7dab8b5b9afb7184fd384cfd5970f2a4c9060fb8995c41a4a7faa35a3184286
  Stored in directory: c:\users\hp\appdata\local\pip\cache\wheels\a0\16\9c\5473df82468f958445479c59e784896fa24f4a5fc024b0f501
Successfully built clang termcolor
  Attempting uninstall: numpy
    Found existing installation: numpy 1.20.1
    Uninstalling numpy-1.20.1:
      Successfully uninstalled numpy-1.20.1
  Attempting uninstall: h5py
    Found existing installation: h5py 2.10.0
    Uninstalling h5py-2.10.0:
      Successfully uninstalled h5py-2.10.0


In [2]:
# installation des packages
from sklearn import datasets
import numpy as np
import tensorflow as tf
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [3]:
# télécharger la base de donnée
df=datasets.load_breast_cancer()

In [4]:
# découvrir le base de donnée
print(df.DESCR)

.. _breast_cancer_dataset:

Breast cancer wisconsin (diagnostic) dataset
--------------------------------------------

**Data Set Characteristics:**

    :Number of Instances: 569

    :Number of Attributes: 30 numeric, predictive attributes and the class

    :Attribute Information:
        - radius (mean of distances from center to points on the perimeter)
        - texture (standard deviation of gray-scale values)
        - perimeter
        - area
        - smoothness (local variation in radius lengths)
        - compactness (perimeter^2 / area - 1.0)
        - concavity (severity of concave portions of the contour)
        - concave points (number of concave portions of the contour)
        - symmetry
        - fractal dimension ("coastline approximation" - 1)

        The mean, standard error, and "worst" or largest (mean of the three
        worst/largest values) of these features were computed for each image,
        resulting in 30 features.  For instance, field 0 is Mean Radi

In [5]:
df.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [6]:
df.data

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]])

In [7]:
# préparer les données
x=df.data
y=df.target

In [8]:
scaler=StandardScaler()
x_scaled=scaler.fit_transform(x)
x_scaled

array([[ 1.09706398, -2.07333501,  1.26993369, ...,  2.29607613,
         2.75062224,  1.93701461],
       [ 1.82982061, -0.35363241,  1.68595471, ...,  1.0870843 ,
        -0.24388967,  0.28118999],
       [ 1.57988811,  0.45618695,  1.56650313, ...,  1.95500035,
         1.152255  ,  0.20139121],
       ...,
       [ 0.70228425,  2.0455738 ,  0.67267578, ...,  0.41406869,
        -1.10454895, -0.31840916],
       [ 1.83834103,  2.33645719,  1.98252415, ...,  2.28998549,
         1.91908301,  2.21963528],
       [-1.80840125,  1.22179204, -1.81438851, ..., -1.74506282,
        -0.04813821, -0.75120669]])

In [9]:
x_train,x_test,y_train,y_test=train_test_split(x_scaled, y, test_size=0.2, random_state=42)

In [10]:
print(x_train.shape, x_test.shape)

(455, 30) (114, 30)


In [14]:
# construction de réseau de neurone
# création du réseau de neurone
model=tf.keras.models.Sequential()

In [16]:
# ajouter une couche de type dense, nombre des noeuds est 15(la taille de la couche caché intermédiare), fonction d'activation 
#pour couche caché esr RELU, pour sortie est SEGMOID, en spcifie les poids, la taille de la couche d'entrée est 30
model.add(tf.keras.layers.Dense(units=15,activation='relu',kernel_initializer='uniform',input_dim=30))

In [18]:
# ajout de la couche de sortie,dimension est une seul unité, fonction d'activation pour couche de sortie est SEGMOID
model.add(tf.keras.layers.Dense(units=1,activation='sigmoid',kernel_initializer='uniform'))

In [19]:
# la fonction de cout(perte) loss, pour comparer la sortie avec la sortie réelle et faire mise à jour des poids, 
#precision du model: metrics
model.compile(optimizer='adam',loss='binary_crossentropy', metrics=['binary_accuracy'])

In [20]:
# voir mon premier réseau de neuronne
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 15)                465       
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 16        
Total params: 481
Trainable params: 481
Non-trainable params: 0
_________________________________________________________________


In [21]:
# entrainement de réseau de neuronne,lors de la mise à jour des poids faire passer toute le base de donné( batch_size=None), 
#faire passer 10 échontillons( batch_siez=10).
# epochs=combien de fois je vais passer la base de données pour entrainer mon model, donc pour chaque epochs je vais calculer 
#la la fct de cout loss et la metrics.
model.fit(x_train,y_train,batch_size=10,epochs=100)
# le cout va diminuer et la précision va augmenter

Epoch 1/100
46/46 [==============================] - 3s 4ms/step - loss: 0.6422 - binary_accuracy: 0.9143
Epoch 2/100
46/46 [==============================] - 0s 1ms/step - loss: 0.4482 - binary_accuracy: 0.9231
Epoch 3/100
46/46 [==============================] - 0s 1ms/step - loss: 0.2667 - binary_accuracy: 0.9385
Epoch 4/100
46/46 [==============================] - 0s 1ms/step - loss: 0.1839 - binary_accuracy: 0.9473
Epoch 5/100
46/46 [==============================] - 0s 1ms/step - loss: 0.1436 - binary_accuracy: 0.9626
Epoch 6/100
46/46 [==============================] - 0s 1ms/step - loss: 0.1197 - binary_accuracy: 0.9692
Epoch 7/100
46/46 [==============================] - 0s 1ms/step - loss: 0.1048 - binary_accuracy: 0.9736
Epoch 8/100
46/46 [==============================] - 0s 2ms/step - loss: 0.0941 - binary_accuracy: 0.9802
Epoch 9/100
46/46 [==============================] - 0s 1ms/step - loss: 0.0870 - binary_accuracy: 0.9824
Epoch 10/100
46/46 [==========================

In [24]:
#tester et evaluer le réseau de neuronne
test_loss, test_accuracy=model.evaluate(x_test,y_test)
print(f'Test loss {test_loss} et Test accuracy {test_accuracy}')
# model bien précis

4/4 [==============================] - 0s 1ms/step - loss: 0.0591 - binary_accuracy: 0.9825
Test loss 0.05912569537758827 et Test accuracy 0.9824561476707458
